name: Autogenerador WebGrabPlus

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-wg:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar archivos del repositorio
      uses: actions/checkout@v4

    - name: Preparar carpetas para WebGrab+Plus
      run: |
        mkdir -p config/siteini.user
        cp WebGrab++.config.xml config/WebGrab++.config.xml
        cp elmundo.es.ini config/siteini.user/elmundo.es.ini

    - name: Ejecutar WebGrab+Plus mediante Docker oficial
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/config:/config \
          lscr.io/linuxserver/webgrabplus:latest \
          /app/dotnet/dotnet /app/wg++/bin.net/WebGrab+Plus.dll /config

    - name: Mover archivo EPG generado a la raíz
      run: |
        # Buscamos el archivo guiatv.xml dentro de la carpeta config y sus subcarpetas y lo traemos a la raíz
        find config/ -name "guiatv.xml" -exec mv {} . \;
        
        # Forzamos una comprobación visual en la consola para confirmar que el archivo está aquí
        ls -la guiatv.xml || echo "ERROR: El archivo guiatv.xml no se encuentra en la raíz"

    - name: Guardar la guía generada en GitHub
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        # Verificamos si el archivo existe antes de intentar añadirlo a Git para evitar el error 128
        if [ -f guiatv.xml ]; then
          git add guiatv.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "EPG actualizada con WebGrab+ Docker" && git push)
        else
          echo "No se encontró el archivo guiatv.xml para subir."
          exit 1
        fi
