name: Actualizar mi EPG Diariamente

on:
  schedule:
    - cron: '0 4 * * *' # Se ejecuta automáticamente todos los días a las 4:00 AM UTC
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-rate: ubuntu-latest
    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Instalar WebGrab+Plus
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete
        wget http://webgrabplus.com
        tar -zxvf WebGrabPlus_V3.3_install.tar.gz
        cd WebGrabPlus.a-linux
        ./install.sh

    - name: Ejecutar la descarga de EPG
      run: |
        cd ~/.WebGrab+Plus
        ./run.sh

    - name: Subir el archivo XML generado
      run: |
        git config --global user.name "EPG Bot"
        git config --global user.email "bot@epg.com"
        mv ~/.WebGrab+Plus/guia_favoritos.xml .
        git add guia_favoritos.xml
        git commit -m "Guía actualizada automáticamente" || exit 0
        git push
